#ifndef dd2md_readLmp_H_
#define dd2md_readLmp_H_

//#ifndef _MODEL_NON_SINGULAR_DD_ 
//#define _MODEL_NON_SINGULAR_DD_ 1 // 0 classical theory, 1 Cai's regularization method, 2 Lazar's regularization method
//#endif

#include <iostream> // debug
#include <string>
#include <tuple>
#include <list>
#include <stdlib.h> // EXIT_SUCCESS, EXIT_FAILURE

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/eigen.h>
#include <pybind11/numpy.h>
#include <pybind11/pytypes.h>
//#include <pybind11/smart_holder.h>
//#include <pybind11/complex.h>

#include <LmpReader.h>

#include <TextFileParser.h>
#include <Polycrystal.h>
//#include <SimplicialMesh.h>
//#include <Grain.h>
//#include <DefectiveCrystal.h>
#include <DislocationDynamicsBase.h>
#include <MicrostructureGeneratorBase.h>
#include <MicrostructureGenerator.h>
#include <DDconfigIO.h>
#include <DDconfigFields.h>
#include <DislocationLoopPatches.h>
//#include <DislocationSegment.h>
//#include <DislocationDynamicsModule.h>
#include <UniformExternalLoadController.h>
#include <IDreader.h>
//#include <VTKsegments.h>
#include <string>
#include <Eigen/Core>
#include <Eigen/Dense>
#include <Eigen/LU>

//#include <ddpy.h>
#include <MicrostructureGeneratorBaseInMem.h>
#include <MicrostructureGeneratorInMem.h>
#include <MicrostructureSpecification.h>

namespace py = pybind11;
namespace model
{
class AtomDisplacementGenerator
{
   private:
      typedef Eigen::Matrix<double,3,1> VectorDim;
      typedef Eigen::Matrix<double,3,3> MatrixDim;
      //typedef std::vector<model::FEMnodeEvaluation<model::LagrangeElement<3,2>,3,1>> fieldPointsType;
      typedef std::vector<VectorDim> fieldPointsType;
      typedef std::vector<size_t> pointIDsType;
      //typedef std::vector<std::vector<double>> fieldPointsType;
      typedef std::vector<std::vector<double>> fieldPointsOutputType;
      typedef model::DislocationDynamicsBase<3> DislocationDynamicsBaseType;
      typedef model::DefectiveCrystal<3,0> DefectiveCrystalType;

      // private data members
      std::string dddPath; // remove, to be found in ddBase
      //std::string meshFilePath; // remove, to be found in ddBase
      std::unique_ptr<DislocationDynamicsBaseType> ddBase;
      std::unique_ptr<DefectiveCrystalType> DC;

      std::string lattice;

      void applyDisplacement( VectorDim& x);

      // matrix to squeeze slip system geometry of lammps configuration
      //  to make those slip systems align with modelib slip systems
      MatrixDim lmpDeformationMatrix;
      MatrixDim lmpDeformationMatrixInverse;
      
      MatrixDim C2G; // [[ss],[nn x ss],[nn]
      MatrixDim C2Ginv; // [[ss],[nn x ss],[nn]

      // Because I'd like to read the microstructure generated by
      //  runGlidesteps, keep the DDconfigIO outside of a
      //  MicrostructureGenerator.
      DDconfigIO<3> configIO;

      //MicrostructureGenerator microstructureGenerator;
      std::unique_ptr<DDconfigFields<3>> configFields;

      //void readMicrostructure();
      //void writeConfiguration( const size_t& runID);
      double solidAngle( const VectorDim& x) const;
      double solidAngle(
            const double& x,
            const double& y,
            const double& z
            ) const;

      VectorDim dislocationPlasticDisplacement( const VectorDim& x) const;
      VectorDim dislocationPlasticDisplacement(
            const double& x,
            const double& y,
            const double& z
            ) const;
      //

      //size_t atomPopulationCount;
      //size_t atomTypeCount;
      std::vector<double> lammpsBoxBounds; // xlo xhi ylo yhi zlo zhi
      std::vector<double> lammpsTiltFactors; // xy xz yz
      //std::vector<double> lammpsDeformedBoxBounds;
      //std::vector<double> lammpsDeformedTiltFactors;
      //std::vector<double> lammpsDeformedBoxDimensions;
      std::map<size_t, double> masses; // per atom type

      std::vector<size_t> atomIDs; // per atom
      std::vector<size_t> atomTypes; // per atom

      fieldPointsType fieldPoints;
      fieldPointsType displacements;
      pointIDsType pointIDs;
      std::vector<VectorDim> elasticDisplacements;

      std::vector<std::string> acceptableLattices;//({"bcc","fcc"});
      std::vector<std::string> acceptableMaterials;//({"Cu","Fe_320"});

      //bool alignToSlipSystem0;
      bool debugFlag;
      double burgersMagnitude;
      int solidSolutionNoiseMode;
      int stackingFaultNoiseMode;

      // private function members
      void applyExternalElasticField();
      void resetStaticIDs();
      void readddBase();
      void shift_atoms();//fieldPointsType& fieldPointsIn);

      // 
      std::pair<int,int> limit_denominator(
         const double& xxIn,
         const int& max_denominator
         );
      // 
      const DDconfigIO<3>& config() const;
      DDconfigIO<3>& config();
      // 

   public:
      void readConfiguration( const size_t& runID);
      void readLammpsConfigurationFile(
            const std::string& lammpsDataFilePath
            );
      void readBurgersMagnitude( const std::string& materialPath);
      void setCurrentStep( const long int& step);
      // constructor
      AtomDisplacementGenerator(
            const std::string& modelibFolderPath
            //const std::string& meshFilePathIn
           ) :
         dddPath( modelibFolderPath)
         , lmpDeformationMatrix( Eigen::Matrix<double,3,3>::Identity())
         , lmpDeformationMatrixInverse( Eigen::Matrix<double,3,3>::Identity())
         , configIO( modelibFolderPath + "/evl")
         , acceptableLattices( std::vector<std::string>({"bcc","fcc"}))
         , acceptableMaterials( std::vector<std::string>({"Fe_320","Cu"}))
         , debugFlag( true)
         , burgersMagnitude( -1.0)
         , solidSolutionNoiseMode( 0)
         , stackingFaultNoiseMode( 0)
      {
         resetStaticIDs();
      };

      std::list<std::shared_ptr<model::MicrostructureSpecification>> microstructureSpecifications;

      // public function members
      double getBurgersMagnitude();
      void readDefectiveCrystal();
      void setOutputPath( const std::string& outputPath);

      void regenerateMicrostructure(); // reads from inputFiles/initialMicrostructure.txt
      void generateMicrostructure(); // uses microstructureSpecifications
      void clearMicrostructureSpecifications();
      void specifyDipoles(
         const std::string& tag,
         const std::vector<int>& slipSystemIDs,
         const std::vector<int>& exitFaceIDs,
         const pybind11::array_t<double,
                  pybind11::array::c_style | pybind11::array::forcecast>&
                  pointsIn,
         const std::vector<double>& heights,
         const std::vector<int>& nodes,
         const std::vector<double>& glideSteps
         );

      void specifyLoops(
         const std::string& tag,
         const std::vector<int>& slipSystemIDs,
         const std::vector<double>& loopRadii,
         const std::vector<long int>& loopSegmentCounts, //periodicLoopSides
         const pybind11::array_t<double,
                  pybind11::array::c_style | pybind11::array::forcecast>&
                  loopCenters
         );
      void specifyLoopDensity(
               const std::string& tag,
               const double& periodicLoopTargetDensityIn,
               const long int& periodicLoopSegmentCountIn,
               const double& periodicLoopRadiusDistributionMeanIn,
               const double& periodicLoopRadiusDistributionStdIn
         );
      void specifyLoopDensitiesPerSlipSystem(
               const std::string& tag,
               const std::map<int, double>& loopDensitiesPerSlipSystemIn,
               const long int& periodicLoopSegmentCountIn,
               const double& periodicLoopRadiusDistributionMeanIn,
               const double& periodicLoopRadiusDistributionStdIn
         );
      void specifyPrismaticLoops(
         const std::string& tag,
         const std::vector<int>& slipSystemIDs,
         const std::vector<double>& prismaticLoopRadii,
         const pybind11::array_t<double,
                  pybind11::array::c_style | pybind11::array::forcecast>&
                  prismaticLoopCenters,
         const std::vector<double>& prismaticLoopSteps
         );
      void specifyPrismaticLoopDensity(
               const std::string& tag,
               const double& prismaticLoopTargetDensityIn,
               const double& prismaticLoopRadiusDistributionMeanIn,
               const double& prismaticLoopRadiusDistributionStdIn,
               const double& prismaticLoopStepDistributionMeanIn,
               const double& prismaticLoopStepDistributionStdIn
         );
      void specifyPrismaticLoopDensitiesPerSlipSystem(
               const std::string& tag,
               const std::map<int, double>& prismaticLoopDensitiesPerSlipSystemIn,
               const double& prismaticLoopRadiusDistributionMeanIn,
               const double& prismaticLoopRadiusDistributionStdIn,
               const double& prismaticLoopStepsDistributionMeanIn,
               const double& prismaticLoopStepsDistributionStdIn
         );
      void specifyDipoleDensity(
               const std::string& tag,
               const double& periodicDipoleTargetDensityIn
         );

      //void computeDisplacements( const std::string& lammpsFilePath);
      void computeDisplacements();
      void applyDisplacements();
      void writeConfigurationToFile( const std::string& outputFilePath);
      //void computeDisplacements2( const std::string& lammpsFilePath);
      void computeDisplacements2();
      //void computeDisplacement( );
      void writeDisplacementsToLammpsFile(
            const std::string& outputFilePath);
      std::map< size_t, VectorDim> //py::array_t<double, py::array::c_style> >
         getDisplacementsMap();
      py::array_t<double, py::array::c_style>
         getDisplacementsNumpy();
      void readLammpsBox( const std::string& lammpsDataFilePath);
      std::tuple<
         py::array_t<double, py::array::c_style>, // planeNormals
         py::array_t<double, py::array::c_style>, // Burger's vectors
         std::map< int,
            std::map< int,
               py::array_t<double, py::array::c_style>
               >
            > // polygons
         > getPatchGlidePlanes();
      void regeneratePolycrystalFile(
            const py::array_t<double,
               py::array::c_style | py::array::forcecast>
               grain1globalX1,
            const py::array_t<double,
               py::array::c_style | py::array::forcecast>
               grain1globalX3,
            const py::array_t<int,
               py::array::c_style | py::array::forcecast>
               boxScaling, // number of unit cells per box direction
            const py::array_t<int,
               py::array::c_style | py::array::forcecast>
               boxEdges1,
            const py::array_t<int,
               py::array::c_style | py::array::forcecast>
               boxEdges2,
            const py::array_t<int,
               py::array::c_style | py::array::forcecast>
               boxEdges3,
            const double& TT,
            const int& enablePartials,
            const std::string& latticeIn,
            const std::string& materialIn,
            const std::string& meshFilePathIn,
            //const py::array_t<double,
            //   py::array::c_style | py::array::forcecast>
            //   X0, // mesh nodes are mapped to x=F*(X-X0)
            const py::array_t<double,
               py::array::c_style | py::array::forcecast>
               periodicFaceIDs
            );
      void runGlideSteps( const size_t& stepsToRun);
}; // AtomDisplacementGenerator

/**********************************************************************/
} // d2md namespace
#endif
