#ifndef dd2md_readLmp_H_
#define dd2md_readLmp_H_

//#ifndef _MODEL_NON_SINGULAR_DD_ 
//#define _MODEL_NON_SINGULAR_DD_ 1 // 0 classical theory, 1 Cai's regularization method, 2 Lazar's regularization method
//#endif

#include <iostream> // debug
#include <string>
#include <tuple>
#include <list>
#include <stdlib.h> // EXIT_SUCCESS, EXIT_FAILURE

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/eigen.h>
#include <pybind11/numpy.h>
#include <pybind11/pytypes.h>
//#include <pybind11/smart_holder.h>
//#include <pybind11/complex.h>

#include <LmpReader.h>

#include <TextFileParser.h>
#include <Polycrystal.h>
//#include <SimplicialMesh.h>
//#include <Grain.h>
//#include <DefectiveCrystal.h>
#include <DislocationDynamicsBase.h>
#include <MicrostructureGeneratorBase.h>
#include <MicrostructureGenerator.h>
#include <DDconfigIO.h>
#include <DDconfigFields.h>
#include <DislocationLoopPatches.h>
//#include <DislocationSegment.h>
//#include <DislocationDynamicsModule.h>
#include <UniformExternalLoadController.h>
#include <IDreader.h>
//#include <VTKsegments.h>
#include <string>
#include <Eigen/Core>
#include <Eigen/Dense>
#include <Eigen/LU>

namespace py = pybind11;
namespace model
{
class AtomDisplacementGenerator
{
   private:
      typedef Eigen::Matrix<double,3,1> VectorDim;
      typedef Eigen::Matrix<double,3,3> MatrixDim;
      //typedef std::vector<model::FEMnodeEvaluation<model::LagrangeElement<3,2>,3,1>> fieldPointsType;
      typedef std::vector<VectorDim> fieldPointsType;
      typedef std::vector<size_t> pointIDsType;
      //typedef std::vector<std::vector<double>> fieldPointsType;
      typedef std::vector<std::vector<double>> fieldPointsOutputType;
      typedef model::DislocationDynamicsBase<3> DislocationDynamicsBaseType;
      typedef model::DefectiveCrystal<3,0> DefectiveCrystalType;

      // private data members
      std::string dddPath; // remove, to be found in ddBase
      std::string meshFilePath; // remove, to be found in ddBase
      std::unique_ptr<DislocationDynamicsBaseType> ddBase;
      std::unique_ptr<DefectiveCrystalType> DC;

      std::string lattice;

      void applyDisplacement( VectorDim& x);

      // matrix to squeeze slip system geometry of lammps configuration
      //  to make those slip systems align with modelib slip systems
      MatrixDim lmpDeformationMatrix;
      MatrixDim lmpDeformationMatrixInverse;
      
      MatrixDim C2G; // [[ss],[nn x ss],[nn]

      // Because I'd like to read the microstructure generated by
      //  runGlidesteps, keep the DDconfigIO outside of a
      //  MicrostructureGenerator.
      DDconfigIO<3> configIO;

      //MicrostructureGenerator microstructureGenerator;
      std::unique_ptr<DDconfigFields<3>> configFields;

      //void readMicrostructure();
      //void writeConfiguration( const size_t& runID);
      double solidAngle( const VectorDim& x) const;
      double solidAngle(
            const double& x,
            const double& y,
            const double& z
            ) const;

      VectorDim dislocationPlasticDisplacement( const VectorDim& x) const;
      VectorDim dislocationPlasticDisplacement(
            const double& x,
            const double& y,
            const double& z
            ) const;
      //

      //size_t atomPopulationCount;
      //size_t atomTypeCount;
      std::vector<double> lammpsBoxBounds; // xlo xhi ylo yhi zlo zhi
      std::vector<double> lammpsDeformedBoxBounds;
      std::vector<double> lammpsDeformedBoxDimensions;
      std::map<size_t, double> masses; // per atom type

      std::vector<size_t> atomIDs; // per atom
      std::vector<size_t> atomTypes; // per atom

      fieldPointsType fieldPoints;
      pointIDsType pointIDs;
      std::vector<VectorDim> elasticDisplacements;

      std::vector<std::string> acceptableLattices;//({"bcc","fcc"});
      std::vector<std::string> acceptableMaterials;//({"Cu","Fe_320"});

      //bool alignToSlipSystem0;
      bool debugFlag;
      double skew;
      double burgersMagnitude;
      int solidSolutionNoiseMode;
      int stackingFaultNoiseMode;

      // private function members
      void applyExternalElasticField();
      void resetStaticIDs();
      void readddBase();
      void setCurrentStep( const long int& step);
      void shift_atoms();//fieldPointsType& fieldPointsIn);

      // 
      const DDconfigIO<3>& config() const;
      DDconfigIO<3>& config();
      // 

   public:
      void readConfiguration( const size_t& runID);
      void readLammpsConfigurationFile(
            const std::string& lammpsDataFilePath
            );
      void readBurgersMagnitude( const std::string& materialPath);
      // constructor
      AtomDisplacementGenerator(
            const std::string& modelibFolderPath
            //const std::string& meshFilePathIn
           ) :
         dddPath( modelibFolderPath)
         , lmpDeformationMatrix( Eigen::Matrix<double,3,3>::Identity())
         , lmpDeformationMatrixInverse( Eigen::Matrix<double,3,3>::Identity())
         , configIO( modelibFolderPath + "/evl")
         //, alignToSlipSystem0( true)
         //, meshFilePath( meshFilePathIn)
         , acceptableLattices( std::vector<std::string>({"bcc","fcc"}))
         , acceptableMaterials( std::vector<std::string>({"Fe_320","Cu"}))
         , debugFlag( true)
         , skew( 0.0)
         , burgersMagnitude( -1.0)
         , solidSolutionNoiseMode( 0)
         , stackingFaultNoiseMode( 0)
      {
         resetStaticIDs();
      };

      // public function members
      double getBurgersMagnitude();
      void readDefectiveCrystal();
      void regenerateMicrostructure();
      //void computeDisplacements( const std::string& lammpsFilePath);
      void computeDisplacements();
      void writeConfigurationToFile( const std::string& outputFilePath);
      //void computeDisplacements2( const std::string& lammpsFilePath);
      void computeDisplacements2();
      //void computeDisplacement( );
      void writeDisplacementsToFile( const std::string& outputFilePath);
      void readLammpsBounds( const std::string& lammpsDataFilePath);
      std::tuple<
         py::array_t<double, py::array::c_style>, // planeNormals
         py::array_t<double, py::array::c_style>, // Burger's vectors
         std::map< int,
            std::map< int,
               py::array_t<double, py::array::c_style>
               >
            > // polygons
         > getPatchGlidePlanes();
      void regeneratePolycrystalFile(
            const py::array_t<double,
               py::array::c_style | py::array::forcecast>
               c2g,
               const std::string& latticeIn,
               const std::string& materialIn,
               const std::string& meshFilePathIn
            );
      void runGlideSteps( const size_t& stepsToRun);
}; // AtomDisplacementGenerator

/**********************************************************************/
} // d2md namespace
#endif
